checkstyle/java.gradle, jacoco.gradle, versions.gradle
=> 💎 Updated dependencies

README.md, quality/findbugs/android.gradle
Putting them in as `provided` dependency will break clients consuming libraries without the dependency.
Do we want these annotations as transitive dependency? -> I don't think so. But annotations are the best way to suppress the warnings IMO
=> fix: remove findbugs annotations dependency because they are `Class` retention

README.md, quality/pmd/pmd-ruleset.xml
Exclude `AvoidFieldNameMatchingMethodName` rule from pmd rule set to avoid unnecessary errors as there is nothing mentioned in google style about getters and setters.
=> quality(pmd) exculde `AvoidFieldNameMatchingMethodName` rule by default.

README.md, quality/findbugs/android.gradle
to provide a complete classpath to findbugs we traverse project
dependencies, collecting all jars and aars from local `project` type
dependencies. we extract the `classes.jar` from aars and the put all the
jars on findbugs classpath.
This logic is shared with doclava, so I extracted the aar-unzipping into
a shared util. See `util/unzipAar.gradle` doc comment for usage
instructions.
closes #8
=> quality(findbugs): setup complete classpath

README.md, documentation/README.md, documentation/doclava/android.gradle
Rationale: we have projects that organize code in multiple projects but
still want to generate a combined javadoc for SDK users.
I intend to tag `1.2.0` after this is merged
=> feat: allow project to configure custom source set for doclava javadoc

README.md, documentation/doclava/android.gradle
this way sibling projects can create their own javadoc without the
sibling image assets.
This breaks existing javadoc/doclava configs, so we'll bump the version
to `2.0`.
=> feat(doc): make javadoc image assets project local

README.md, versions/versions.gradle
In order to validate behavior on API level 27, samples and QA app should target 27.
Also updating build sdk and plugin versions, which are lagging behind a bit.
=> 💎 Update AGP, build and target SDK

quality/checkstyle/checkstyle.xml, quality/checkstyle/java.gradle
Removes `SingleLineJavadoc` to accept google formatted code.
The google code formatter generates single line javadoc comments but the
google code style checkstyle config complains about them. in order to
use both the code formatter and still get warnings about style
problems (e.g. missing javadoc or variable names) I suggest we deviate
from the checkstlye ruleset provided by google to actually match their
formatter.
The code formatter was generating annotation indentation that violates
the google code style, which was fixed in 1.6 see google/google-java-format#159
and google/google-java-format@a268700
=> quality(checkstyle): remove inconsistent rule & update code formatter

quality/checkstyle/java.gradle, quality/checkstyle/pre-commit
`./gradlew installPrecommitHook` backs up existing hook
The hook formats all changed files (staged or unstaged) and outputs a
warning about other files that do not conform to google code style
=> quality(style): add task that installs a precommit hook that format code

versions/versions.gradle
This disables compatibility mode in Android Pie. Projects updating to this commit should review the various [behavioral changes](https://developer.android.com/about/versions/pie/android-9.0-changes-28) and fix their code accordingly.
=> 🔺 Raise target SDK to 28

versions/versions.gradle
Volley 1.0.0 depends on Apache HTTP, however API 28 removed it as a dependency in the bootclasspath. Volley 1.1.0 makes Apache HTTP an optional dependency.
=> Update Volley to v1.1.1

documentation/doclava/android.gradle, versions/versions.gradle
Calling 'Configuration#files' resolves the configuration. This can cause issues with some gradle plugins such as 'kotlin-androidd' because it depends on the configurations not being resolved yet. Moving this call to 'Project#afterEvaluate' avoids these issues.
=> fix: (Doclava) Apply docletpath after project evaluate

quality/jacoco/android.gradle
Jacoco was failing to find the executionData on some systems (Linux) because the variant name wasn't capitalized correctly. This particularly causes problems on CircleCi because builds run in Linux containers.
=> jacoco: Change variant name to capitlized for executionData

quality/jacoco/android.gradle
I missed this before somehow 😣
=> fix: Fix typo in variable name in Jacoco file

quality/README.md, quality/detekt/android.gradle, quality/detekt/detekt-config.yml
Detekt was previously using the cli version, but there is now a Gradle plugin available. There have also been some rules added and changed, so the rule config has been slightly updated. Detekt also now has a ruleset that applies all of the formatting rules from KtLint, so I have also added instructions for this to the readme.
=> Update detekt to the gradle plugin

publish/README.md, publish/bintray.gradle
I accidentally left android-remote-config in for the package name, so this would cause packages to get published there instead of the correct package
=> fix: (publish) Make env variable for bintray package name

quality/errorprone/android.gradle
I ran into the following problem:
```
> Task :some-sdk:compileDebugAndroidTestJavaWithJavac FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':some-sdk:compileDebugAndroidTestJavaWithJavac'.
> NullAway is not a valid checker name
```
and found that other users experienced the same issue -> https://github.com/uber/NullAway/issues/247
this is maybe not the minimal solution, but solved the problem for me.
=> fix: add nullaway to `errorprone` configuration

versions/versions.gradle
This version of AGP requires Gradle v5.6.4 or higher
=> Update android gradle plugin to v3.6.2

documentation/README.md, documentation/doclava/android.gradle
This is so failOnError can be disabled. Normally it should not be disabled, but sometimes it needs to be temporarily disabled due to conflicts with dependencies.
=> (documentation) Add failOnError parameter for DocLava

README.md, index.gradle, publish/README.md, publish/android.gradle
- publish: Replace publishing plugin with AGPs built-in maven-publish
- Remove the requirement for a dependency on digital.wup.android-maven-publish as this plugin has been deprecated and AGP now has built-in support for maven publishing. This means that the 'publications' block must now be declared within a 'afterEvaluate' block.
- publish: Add 'excludeSourceJar' config option
- Sometimes the sources Jar should not be published - such as when the published AAR is minified/obfuscated
- Add 'property' closure to CONIFG
- This can be used to return a value that has been set as either an environment variable or gradle property. Use like this: 'CONFIG.property('PROPERTY_NAME')'
- Update readme for v4.0.0
=> Maven publishing plugin updates - also bump to v4.0.0

README.md, circleci/README.md, circleci/android-sdk/README.md, circleci/android-sdk/config.yml, circleci/app-center/README.md, circleci/app-center/config.yml
CircleCI Orbs allow us to share CI configuration across repos. See the docs for more information: https://circleci.com/docs/2.0/orb-intro/
This has the configuration for two orbs:
- android-sdk: Specifically for building and publishing our Android SDK projects
- app-center: Generic Orb for publishing to App Center (surprisingly I couldn't find an Orb already available for this)
I have already published development versions of these Orbs to `rakutentech/android-sdk@dev:0.1.0` and `rakutentech/app-center@dev:0.1.0`. I've tested this on my forked Mini App repo here: 
https://github.com/corycaywood/android-miniapp/blob/ci/orbs/.circleci/config.yml
=> Add CircleCI Orb configuration for android-sdk and app-center

circleci/android-sdk/README.md, circleci/android-sdk/config.yml
CircleCI recently updated their Android images to use Java 11 instead of 8. This breaks all of our builds currently, so this commit pins the Android image at the last version which used Java 8. See https://github.com/circleci/circleci-images/issues/503.
=> fix: (CircleCI) Pin the android image at api-29 w/ Java 8

README.md, circleci/app-center/README.md, circleci/app-center/config.yml, publish/README.md, publish/bintray.gradle
- Remove bintray plugin and set bintray credentials using maven-publish instead
- The bintray plugin seems to be incompatible with the new Android maven-publish plugin. Setting up the credentials and URL manually isn't difficult, so I've just removed the plugin. This change doesn't affect the end required environment variables - it just means that the bintray plugin no longer needs to be added to the project dependnencies.
- (circleci) App center: add quotes around release notes
- This was failing to upload because the string variable is just directly inserted into the command without treating it as a string.
=> Publishing fixes

README.md, circleci/android-sdk/README.md, circleci/android-sdk/config.yml, publish/README.md, publish/base-artifact.gradle, publish/java.gradle
The [Manifest Config](https://github.com/rakutentech/android-manifest-config) project is a Java library, so we need a slightly different publication configuration for this.
Sorry it looks like a lot of changes, but basically the content of the new `base-artifact.gradle` is almost the same as `android.gradle` was. I just split it into a new file so it can be shared with `java.gradle`. The configuration is almost the same for Java libraries, just the `component` and `sources` are different.
=> feat: Add publication configuration for Java libraries

_includes/head.html
This fix is for the Github pages theme.
The jekyll-seo-tag plugin is no longer supported by Github Pages, so the seo tag was causing the pages build to fail. Instead I've replaced it with the same content that the tag was generating.
=> (gh-pages-theme) fix: Remove SEO tag and replace with content

circleci/android-sdk/README.md, circleci/android-sdk/config.yml
Previously we were using a fixed version of the docker image which supported Java 8. However, in order to target Android 31 you must build with Java 11, so we must update the docker image to a version which supports Java 11.
=> build: Update CircleCI docker image to api-30

README.md, documentation/README.md, documentation/dokka/android.gradle
This is a breaking change and any project which is currently using Dokka v0.10.0 will need to be updated. This change was necessary becuase the older version of Dokka does not support Kotlin >= 1.4.0
=> feat: Added support for Dokka v1.6.10

README.md, publish/releases/README.md, publish/releases/github-api.gradle, quality/gitleaks/build.gradle
The plugin will create a new Github release and upload the modules mappings zip file to releases assets when the `./gradlew githubRelease` task is executed.
=> feat: create github release plugin (SDKCF 4936)

git-hooks/build.gradle, index.gradle, quality/README.md, quality/checkstyle/java.gradle, quality/gitleaks/build.gradle
Changed the plugin to create the git-hook files only if the plugin is installed in the host project.
Fix the CI environment variable ENABLE_GITLEAKS  type.
=> refactor: make githook plugin optional (SDKCF-2623)

README.md, buildSrc/src/test/resources/build_script_dependency.gradle, versions/versions.gradle
Bumped android.plugin to 7.2.0 to fix Dependencycheck reported vulnerabilities.
=> chore: bump android.plugin to 7.2.0 (SDKCF-4918)

danger/Dangerfile
Removed logging `ticketnos` as it's causing invalid Danger issue when used with interpolated #{ticket_pattern}
=> fix: fix invalid Dangerfile error when there are app updates and no changelog (SDKCF-5946)
